kind: pipeline
type: docker
name: run-tests
identifier: YAML_first_ex ## A unique Id for the pipeline.
projectIdentifier: default_project ## Specify the project this pipeline belongs to.
orgIdentifier: default ## Specify the organization this pipeline belongs to.

stages:
  - stage:
      name: Maven Test Stage
      identifier: maven_test_stage
      type: CI
      spec:
        execution:
          steps:
            - step:
                type: Run
                name: Run Maven Tests
                identifier: run_maven_tests
                image: maven:3.9.9-openjdk-21
                commands:
                  - mvn clean test 